### ISSUE TITLE
리액트 문서 한국어 번역 프로젝트

### ISSUE THREAD

**Issue by sairion** [reactkr/discuss#4]
### Contribution how-to

https://github.com/reactkr/react

저장소를 fork하여 'translation' 브랜치로 PR을 넣어주시면 됩니다. 이 프로젝트에서의 번역 스코프는 `/docs/docs/` 안의 api와 react core/addons 등의 작동을 설명하는 부분으로 제한합니다.
### Rules
1. `translation` 브랜치는 원본을 유지하기 위해서 계속적으로 리베이스할 예정입니다. (적어도 일주일에 한번) 따라서 커밋에 **번역하는 원본의 커밋해시를 적어주셔야 합니다.**
2. **작업을 진행중이실 때는 아래의 이슈에 번역 진행이 겹치지 않도록 진행 상황을 써 주시기 바랍니다.**
3. **머지가 먼저 되는 것이 우선적으로 적용됩니다.** 겹칠 경우 별도의 수정 PR을 보내주시기 바랍니다.
4. https://github.com/reactkr/discuss/wiki/glossary 에 용어 번역들을 써 놓도록 합시다.
5. 파일명은 `ID.ko-KR.md` 형식입니다. (예: `thinking-in-react.md` -> `thinking-in-react.ko-KR.md
   `)
6. 문서 헤더의 id 필드는 `ID-ko-KR` 형식으로, permalink 필드는 `ID-ko-KR.html` 형식으로 적어주세요. 실제 HTML 파일은 permalink를 기준으로 생성되므로 prev, next 필드 및 문서 내용의 링크 또한 `ID-ko-KR.html`으로 걸어야 합니다.
### State of React docs translation

https://github.com/facebook/react/search?q=chinese&type=Issues&utf8=%E2%9C%93

현재 중국어 번역 컨트리뷰터들이 `docs/docs` 안의 문서들을 위주로 기여해나가고 있으며 완벽한 상태는 아닙니다. 또한 공식 웹사이트의 i18n이 완벽하게 이뤄진 상태는 아닙니다만, 공식 문서에 머지되어 지킬로 서빙되는 url을 변경하면 중국어로 된 문서를 볼 수 있는 상태입니다. 차후 다른 많은 언어의 문서가 머지되면 지킬의 빌트인 기능을 이용하든 자체 사이트를 구축하든 i18n 지원이 이뤄지지 않을까 추측합니다.
### 번역 to-dos
- [x] 01-why-react.md
- [x] 02-displaying-data.md
- [x] 02.1-jsx-in-depth.md - @marocchino 
- [x] 02.2-jsx-spread.md - @marocchino 
- [x] 02.3-jsx-gotchas.md - @marocchino 
- [x] 03-interactivity-and-dynamic-uis.md
- [x] 04-multiple-components.md
- [x] 05-reusable-components.md - @seoh 
- [x] 06-transferring-props.md - @seoh 
- [x] 07-forms.md
- [x] 08-working-with-the-browser.md - @arkist 
- [x] 08.1-more-about-refs.md - @arkist 
- [x] 09-tooling-integration.md - @marocchino 
- [x] 10-addons.md - @marocchino 
- [x] 10.1-animation.md - @marocchino 
- [x] 10.2-form-input-binding-sugar.md - @marocchino 
- [x] 10.3-class-name-manipulation.md - @marocchino 
- [x] 10.4-test-utils.md - @marocchino 
- [x] 10.5-clone-with-props.md - @marocchino 
- [x] 10.6-update.md
- [x] 10.7-pure-render-mixin.md - @marocchino 
- [x] 10.8-perf.md - @marocchino 
- [x] 11-advanced-performance.md - @arkist 
- [x] complementary-tools.md
- [x] examples.md
- [x] flux-overview.md
- [x] flux-todo-list.md
- [x] getting-started.md
- [x] ref-01-top-level-api.md
- [x] ref-02-component-api.md
- [x] ref-03-component-specs.md
- [x] ref-04-tags-and-attributes.md
- [x] ref-05-events.md - @marocchino 
- [x] ref-06-dom-differences.md - @marocchino 
- [x] ref-07-special-non-dom-attributes.md - @marocchino 
- [x] ref-08-reconciliation.md - @dittos
- [x] ref-09-glossary.md
- [x] thinking-in-react.md
- [x] tutorial.md - @arkist 
- [x] videos.md
- [x] conferences.md - @arkist

**Comment by sairion** [comment]
02 는 제가 작업중입니다.

**Comment by arkist** [comment]
getting-started.md 작업하겠습니다

**Comment by marocchino** [comment]
03 작업중입니다.

**Comment by marocchino** [comment]
04도 제가 하죠.

**Comment by dittos** [comment]
ref-01, ref-02, ref-03 예약합니다. :raised_hands:

**Comment by seoh** [comment]
Flux쪽 하겠습니다.
- flux-overview.md
- flux-todo-list.md

를 쓰고 나니까 옮겨져있네요.

**Comment by seoh** [comment]
thinking-in-react.md 예약

**Comment by jeyraof** [comment]
@seoh 이런, 시작하셨나요?
https://github.com/reactkr/react/pull/7
작업중이기는 했습니다. 회사에 있어서 월요일날 피드백 수정할 예정이었는데

**Comment by seoh** [comment]
방금 맨 앞 문단 정도는 했는데 다른걸봐야겠네요. 저쪽 이슈는 확인 못봤네요.

**Comment by jeyraof** [comment]
적어둘걸.. 죄송합니다.

**Comment by seoh** [comment]
아닙니다. 빨리 말씀해주셔서 다행입니다. 
- 05-reusable-components.md
- 06-transferring-props.md

그럼 04까지 진행중인 것 같으니 05, 06 하겠습니다.

**Comment by dittos** [comment]
오늘은 ref-09를 하겠습니다.

**Comment by dittos** [comment]
ref-08도 미리 맡아두겠습니다.

**Comment by marocchino** [comment]
07 예약하겠습니다.

**Comment by arkist** [comment]
Tutorial 작업합니다

**Comment by jeyraof** [comment]
10.6-update 작업하고있습니다.

**Comment by marocchino** [comment]
flux는 제가 날로 먹겠습니다!

**Comment by sairion** [comment]
:+1: 빠르게 진행되어가네요! 머지된 것들을 업데이트해보니 숫자만 보면 벌써 거의 1/3이나 진행됐습니다. (짧은 것도 있지만)

**Comment by marocchino** [comment]
ref 04 예약합니다.
그리고 리스트 갱신좀 해주세요. 'ㅁ'!

**Comment by marocchino** [comment]
ref 05 예약합니다.

**Comment by marocchino** [comment]
ref 06 예약합니다.

**Comment by marocchino** [comment]
ref 07 예약합니다.

**Comment by marocchino** [comment]
02.1 예약합니다.

**Comment by arkist** [comment]
08, 08.1 진행하겠습니다

**Comment by marocchino** [comment]
02.2 예약합니다.

**Comment by marocchino** [comment]
02.3 예약합니다.

**Comment by marocchino** [comment]
09 예약합니다.

**Comment by marocchino** [comment]
10 예약합니다.

**Comment by marocchino** [comment]
10.4 예약합니다.

**Comment by marocchino** [comment]
10.8 예약합니다.

**Comment by marocchino** [comment]
10.7 예약합니다.
목록에 밑에 항목을 추가해주세요.

```
- [ ] conferences
- [ ] 11-advanced-performance
```

**Comment by marocchino** [comment]
10.5 예약합니다.

**Comment by arkist** [comment]
@marocchino 님이 10.x을 쭉 하고 계시니 제가 11을 하죠. 컨퍼런스 페이지도 덤으로 하겠습니다 -,-;

**Comment by marocchino** [comment]
10.3 예약합니다.

**Comment by marocchino** [comment]
10.2 예약합니다.

**Comment by marocchino** [comment]
10.1 예약합니다.

**Comment by marocchino** [comment]
@dittos 리스트 갱신해주세요. ref-08은 진행중이신가요?

**Comment by marocchino** [comment]
별로 안남았으니 후딱하고 치우죠.

**Comment by dittos** [comment]
모두 수고하셨습니다. 0.13 업데이트를 적용하는 작업이 진행중입니다.
